// <auto-generated />
using DarkWar_WebApp.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DarkWar_WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250731084733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("DarkWar_WebApp.Events", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eventname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HaveParticipated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PointsGet")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DarkWar_WebApp.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CP")
                        .HasColumnType("REAL");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViolationlistSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchtowerLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DarkWar_WebApp.Events", b =>
                {
                    b.HasOne("DarkWar_WebApp.Player", null)
                        .WithMany("Events")
                        .HasForeignKey("PlayerID");
                });

            modelBuilder.Entity("DarkWar_WebApp.Player", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
